version: "3"
networks:
  calliope:
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
volumes: 
  calliope_postgres:
services:
  postgres:
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      CALLIOPE_DB_PASSWORD: calliope
    volumes: 
      - calliope_postgres:/var/lib/postgresql/data
    networks:
      calliope: